In [3]:
from dask.distributed import Client

client = Client("tcp://127.0.0.1:33969")
# client = Client(n_workers=4)
client

<Client: 'tcp://127.0.0.1:33969' processes=8 threads=32, memory=134.85 GB>

In [27]:
import numpy as np
import dask.array as da

In [99]:
a = np.arange(1,13)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [87]:
a.shape

(12,)

In [91]:
a.reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [84]:
a

array([ 6, 15, 24, 33])

In [100]:
a = a.reshape(4,3)

In [93]:
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [94]:
a.shape

(4, 3)

In [101]:
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [103]:
a.sum(axis = 1)

array([ 6, 15, 24, 33])

In [104]:
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [107]:
a = a.cumsum()

In [108]:
a

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45, 55, 66, 78])