In [2]:
from dask.distributed import Client

client = Client("tcp://127.0.0.1:50328")
# client = Client(n_workers=4)
client

<Client: 'tcp://127.0.0.1:50328' processes=4 threads=12, memory=34.36 GB>

In [3]:
import numpy as np

In [4]:
a = np.random.seed(123) # setting a seed enables reproducability
a = np.random.randint(1,101,10)
a

array([67, 93, 99, 18, 84, 58, 87, 98, 97, 48])

In [5]:
b = np.random.normal(5,2,20)
b

array([1.76139987, 2.77207117, 4.10511856, 8.33680322, 4.71325505,
       3.7616182 , 3.46113306, 6.15349204, 5.25305184, 2.39702205,
       9.41485487, 6.04548494, 5.93128951, 6.44983045, 7.99165305,
       6.49316118, 2.79802949, 2.17939759, 3.50469737, 3.03026479])

In [6]:
b.shape

(20,)

In [7]:
b = b.reshape(5,4)
b

array([[1.76139987, 2.77207117, 4.10511856, 8.33680322],
       [4.71325505, 3.7616182 , 3.46113306, 6.15349204],
       [5.25305184, 2.39702205, 9.41485487, 6.04548494],
       [5.93128951, 6.44983045, 7.99165305, 6.49316118],
       [2.79802949, 2.17939759, 3.50469737, 3.03026479]])

In [8]:
np.amax(b)

9.41485487036999

In [9]:
np.amax(b, axis=0)

array([5.93128951, 6.44983045, 9.41485487, 8.33680322])

In [10]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(3, 4)

In [11]:
newarr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [12]:
a = np.arange(16)
np.random.shuffle(a)
a

array([ 1, 12, 11, 15,  7,  9, 14,  4, 13,  6,  2,  0,  5, 10,  3,  8])

In [17]:
%%time 
a = a.reshape((4,4))
a

CPU times: user 43 µs, sys: 1e+03 ns, total: 44 µs
Wall time: 47.2 µs


array([[ 1, 12, 11, 15],
       [ 7,  9, 14,  4],
       [13,  6,  2,  0],
       [ 5, 10,  3,  8]])

In [14]:
np.amax(a)

15

In [15]:
np.amax(a, axis=0)

array([13, 12, 14, 15])

In [18]:
np.amax(a, axis=1)

array([15, 14, 13, 10])

In [21]:
numbers = np.array([1, 3, 2, 4])

n = 3


indices = (-numbers).argsort()[:n]

print(indices)

[3 1 2]


In [45]:
import numpy as np
import heapq

x = np.array([1,-5,4,6,-3,3,45,23,21,234,6,11])

In [35]:
%%time
z = heapq.nlargest(2,x)

CPU times: user 19 µs, sys: 0 ns, total: 19 µs
Wall time: 21 µs


In [37]:
%%time
np.amax(x)

CPU times: user 31 µs, sys: 2 µs, total: 33 µs
Wall time: 35.8 µs


234

In [40]:
%%time
max(x)

CPU times: user 9 µs, sys: 0 ns, total: 9 µs
Wall time: 11.9 µs


234

In [23]:
x, z

(array([ 1, -5,  4,  6, -3,  3]), [6, 4, 3])

In [42]:
import timeit
import bottleneck as bn

N,M,K = 10,1000000,100

In [50]:
-bn.partition(-x, 10)[:10]

array([ 11,   6, 234,  21,  23,  45,   3,   1,   6,   4])

In [51]:
bn.partition(-x, 10)[:10]

array([ -11,   -6, -234,  -21,  -23,  -45,   -3,   -1,   -6,   -4])