In [3]:
import numpy as np
import pandas as pd

In [2]:
questions = {
    "Q1": "I would never audition to be on a game show.",
    "Q2": "I am not much of a flirt.",
    "Q3": "I have to psych myself up before I am brave enough to make a phone call.",
    "Q4": "I would hate living with room mates.",
    "Q5": "I mostly listen to people in conversations.",
    "Q6": "I reveal little about myself.",
    "Q7": "I spend hours alone with my hobbies.",
    "Q8": "I prefer to eat alone.",
    "Q9": "I have trouble finding people I want to be friends with.",
    "Q10": "I prefer to socialize 1 on 1, than with a group.",
    "Q11": "I sometimes speak so quietly people sometimes have trouble hearing me.",
    "Q12": "I do not like to get my picture taken.",
    "Q13": "I can keep a conversation going with anyone about anything.",
    "Q14": "I want a huge social circle.",
    "Q15": "I talk to people when waiting in lines.",
    "Q16": "I act wild and crazy.",
    "Q17": "I am a bundle of joy.",
    "Q18": "I love excitement.",
    "Q19": "I'd like to be in a parade.",
    "Q20": "I am a flamboyant person.",
    "Q21": "I am good at making impromptu speeches.",
    "Q22": "I naturally emerge as a leader.",
    "Q23": "I am spontaneous.",
    "Q24": "I would enjoy being a sports team coach.",
    "Q25": "I have a strong personality.",
    "Q26": "I am excited by many different activities.",
    "Q27": "I spend most of my time in fantasy worlds.",
    "Q28": "I often feel lucky.",
    "Q29": "I don't make eye contact when I talk with people.",
    "Q30": "I have a monotone voice.",
    "Q31": "I am a touchy feely person.",
    "Q32": "I would like to try bungee jumping.",
    "Q33": "I tend to be admired by others.",
    "Q34": "I make big physical movements whenever I get excited.",
    "Q35": "I am brave.",
    "Q36": "I am always in the moment.",
    "Q37": "I am involved with my community.",
    "Q38": "I am good an entertaining children.",
    "Q39": "I like formal occasions.",
    "Q40": "I would have to be lost for a very long time before asking help.",
    "Q41": "I do not care about sports.",
    "Q42": "I prefer individual sports to team sports.",
    "Q43": "My parents know nothing about my love life.",
    "Q44": "I mostly listen to people in conversations.",
    "Q45": "I never leave the door to my room open.",
    "Q46": "I make a lot of hand motions when I talk.",
    "Q47": "I take lots of pictures of my activities.",
    "Q48": "When I was a child, I put on fake concerts and plays with my friends.",
    "Q49": "I really like dancing.",
    "Q50": "I would have difficulty describing myself to someone.",
    "Q51": "My life would not make a good story.",
    "Q52": "I am hesitant to give suggestions.",
    "Q53": "I tire out quickly.",
    "Q54": "I never tell people the important things about myself.",
    "Q55": "I avoid going to unknown places.",
    "Q56": "Going to the doctor is always awkward for me.",
    "Q57": "I have not kept up with my old friends over the years.",
    "Q58": "I have not been joyful for quite some time.",
    "Q59": "I hate to ask for help.",
    "Q60": "If I were to die, I would not want there to be a memorial for me.",
    "Q61": "I hate shopping.",
    "Q62": "I love to do impressions.",
    "Q63": "I would be pleased if asked to speak at a funeral.",
    "Q64": "I would never go to a dance club.",
    "Q65": "I find it very hard to tell people I find them attractive.",
    "Q66": "I hate people.",
    "Q67": "I was an outcast in school.",
    "Q68": "I would enjoy being a librarian.",
    "Q69": "I am usually not single.",
    "Q70": "I am able to stand up for myself.",
    "Q71": "I would go surfing regularly if I lived on a beach.",
    "Q72": "I have wanted to be a stand-up comedian.",
    "Q73": "I am a high status person.",
    "Q74": "I work out regularly.",
    "Q75": "I laugh a lot.",
    "Q76": "I like pranks.",
    "Q77": "I am happy with my life.",
    "Q78": "I am never at a loss for words.",
    "Q79": "I feel healthy and vibrant most of the time.",
    "Q80": "I love large parties.",
    "Q81": "I am quiet around strangers.",
    "Q82": "I don't talk a lot.",
    "Q83": "I keep in the background.",
    "Q84": "I don't like to draw attention to myself.",
    "Q85": "I have little to say.",
    "Q86": "I often feel blue.",
    "Q87": "I am not really interested in others.",
    "Q88": "I make people feel at ease.",
    "Q89": "I don't mind being the center of attention.",
    "Q90": "I start conversations.",
    "Q91": "I talk to a lot of different people at parties.",
}

In [3]:
questions = np.array(list(questions.values()))

In [4]:
questions[1]

'I am not much of a flirt.'

In [15]:
data = np.genfromtxt("data/dataset.csv", dtype=int, delimiter="\t")

In [16]:
data = data[1:, :]

In [18]:
print(data)
print(data.shape)
print(data.dtype)

[[   5   51 7107 ...    1   23    3]
 [   5   39 6354 ...    2   25    2]
 [   3   17 5397 ...    2   19    1]
 ...
 [   3   29 6618 ...    2   28    1]
 [   4   15 8321 ...    1   19    1]
 [   5   57 2950 ...    1   25    1]]
(7188, 282)
int64


In [34]:
questions[[0, 1, 2]]

array(['I would never audition to be on a game show.',
       'I am not much of a flirt.',
       'I have to psych myself up before I am brave enough to make a phone call.'],
      dtype='<U72')

In [40]:
data.shape

(7188, 282)

In [41]:
data[data < 12000].shape

(2006429,)

In [45]:
my_array = np.array(
    [[10, 2, 13], [21, 22, 23], [31, 32, 33], [10, 57, 20], [20, 20, 20], [101, 91, 10]]
)

In [48]:
def my_function(x):
#     position = np.argmax(x)
    position = np.max(x)

    return position

In [49]:
print(np.apply_along_axis(my_function, axis=0, arr=my_array))

[101  91  33]


In [99]:
df = pd.DataFrame(my_array)

0    101
1     91
2     33
dtype: int64


In [9]:
def my_function(x):
#     z= x.idxmax()
#     print(x[0], x[1], x[2])
    z= x.max()

    return z

In [ ]:
print(df.apply(my_function, axis=0))

In [74]:
df['yeni'] =df.apply(my_function, axis=1)

10 2 13
21 22 23
31 32 33
10 57 20
20 20 20
101 91 10


In [75]:
df

0   1   2  yeni
0   10   2  13    13
1   21  22  23    23
2   31  32  33    33
3   10  57  20    57
4   20  20  20    20
5  101  91  10   101

In [78]:
?df.nlargest

Signature: df.nlargest(n, columns, keep='first') -> 'DataFrame'
Docstring:
Return the first `n` rows ordered by `columns` in descending order.

Return the first `n` rows with the largest values in `columns`, in
descending order. The columns that are not specified are returned as
well, but not used for ordering.

This method is equivalent to
``df.sort_values(columns, ascending=False).head(n)``, but more
performant.

Parameters
----------
n : int
    Number of rows to return.
columns : label or list of labels
    Column label(s) to order by.
keep : {'first', 'last', 'all'}, default 'first'
    Where there are duplicate values:

    - `first` : prioritize the first occurrence(s)
    - `last` : prioritize the last occurrence(s)
    - ``all`` : do not drop any duplicates, even it means
                selecting more than `n` items.

    .. versionadded:: 0.24.0

Returns
-------
DataFrame
    The first `n` rows ordered by the given columns in descending
    order.

See Also
--------
DataFram

In [79]:
df.nlargest(3, 'yeni')

0   1   2  yeni
5  101  91  10   101
3   10  57  20    57
2   31  32  33    33

In [90]:
%%time
df.nsmallest(3, 'yeni')

CPU times: user 3.52 ms, sys: 0 ns, total: 3.52 ms
Wall time: 1.9 ms


0   1   2  yeni
0  10   2  13    13
4  20  20  20    20
1  21  22  23    23

In [86]:
%%time
df.sort_values('yeni', ascending=True).head(3)

CPU times: user 1.4 ms, sys: 226 µs, total: 1.62 ms
Wall time: 941 µs


0   1   2  yeni
0  10   2  13    13
4  20  20  20    20
1  21  22  23    23

In [30]:
%%time
df_2 = pd.DataFrame(np.random.randint(0,1000000,size=(15000000, 4)), columns=list('ABCD'))

CPU times: user 151 ms, sys: 133 ms, total: 285 ms
Wall time: 283 ms


In [35]:
%%time
df_2

CPU times: user 2 µs, sys: 0 ns, total: 2 µs
Wall time: 4.05 µs


A       B       C       D    yeni
0         109735  750841   38809  732758  109745
1         698075  376011  390876   75236  698085
2         221895  745522   22658  591431  221905
3         745308  856814  943159  756698  745318
4          49214  289206  223074  115007   49224
...          ...     ...     ...     ...     ...
14999995  283147  670557  887237  730826  283157
14999996  560012  578883  101952  796348  560022
14999997  937524  735122  502478   97388  937534
14999998  897672   34514  884937  352366  897682
14999999  948823  226908  976261  529084  948833

[15000000 rows x 5 columns]

In [32]:
%%time
df_2.nlargest(5, 'D')

CPU times: user 370 ms, sys: 143 ms, total: 514 ms
Wall time: 512 ms


A       B       C       D
1569744  586335  472676  773272  999999
4328291   27335  237950  454249  999999
4594259     465  663983  375858  999999
5311363  682777  241884  115121  999999
6620893  526173  315117   89492  999999

In [33]:
%%time
# df_2['yeni'] =df_2.apply(my_function, axis=1)
df_2['yeni'] =df_2.apply(lambda x: x.A+10, axis=1)

CPU times: user 1min 53s, sys: 1.55 s, total: 1min 54s
Wall time: 1min 55s


In [34]:
df_2

A       B       C       D    yeni
0         109735  750841   38809  732758  109745
1         698075  376011  390876   75236  698085
2         221895  745522   22658  591431  221905
3         745308  856814  943159  756698  745318
4          49214  289206  223074  115007   49224
...          ...     ...     ...     ...     ...
14999995  283147  670557  887237  730826  283157
14999996  560012  578883  101952  796348  560022
14999997  937524  735122  502478   97388  937534
14999998  897672   34514  884937  352366  897682
14999999  948823  226908  976261  529084  948833

[15000000 rows x 5 columns]

In [38]:
%%time
df_2.sort_values('yeni', ascending=False).head(5)

CPU times: user 3.45 s, sys: 241 ms, total: 3.69 s
Wall time: 3.74 s


A       B       C       D     yeni
1256367   999999  756727  994474  451308  1000009
14377597  999999  508942   97392  202752  1000009
7496451   999999  550082  994583  697986  1000009
12903382  999999  288053  430699  965492  1000009
13173697  999999  865279  627524  608353  1000009

In [39]:
%%time
df_2.nlargest(5, 'yeni')

CPU times: user 122 ms, sys: 192 ms, total: 314 ms
Wall time: 313 ms


A       B       C       D     yeni
714692   999999  351846  700181  623983  1000009
889628   999999  977761  642884  308138  1000009
1256367  999999  756727  994474  451308  1000009
3319666  999999  860753  351940   20856  1000009
5191601  999999  234714   79172  751578  1000009