In [3]:
import numpy as np
import pandas as pd

In [2]:
questions = {
    "Q1": "I would never audition to be on a game show.",
    "Q2": "I am not much of a flirt.",
    "Q3": "I have to psych myself up before I am brave enough to make a phone call.",
    "Q4": "I would hate living with room mates.",
    "Q5": "I mostly listen to people in conversations.",
    "Q6": "I reveal little about myself.",
    "Q7": "I spend hours alone with my hobbies.",
    "Q8": "I prefer to eat alone.",
    "Q9": "I have trouble finding people I want to be friends with.",
    "Q10": "I prefer to socialize 1 on 1, than with a group.",
    "Q11": "I sometimes speak so quietly people sometimes have trouble hearing me.",
    "Q12": "I do not like to get my picture taken.",
    "Q13": "I can keep a conversation going with anyone about anything.",
    "Q14": "I want a huge social circle.",
    "Q15": "I talk to people when waiting in lines.",
    "Q16": "I act wild and crazy.",
    "Q17": "I am a bundle of joy.",
    "Q18": "I love excitement.",
    "Q19": "I'd like to be in a parade.",
    "Q20": "I am a flamboyant person.",
    "Q21": "I am good at making impromptu speeches.",
    "Q22": "I naturally emerge as a leader.",
    "Q23": "I am spontaneous.",
    "Q24": "I would enjoy being a sports team coach.",
    "Q25": "I have a strong personality.",
    "Q26": "I am excited by many different activities.",
    "Q27": "I spend most of my time in fantasy worlds.",
    "Q28": "I often feel lucky.",
    "Q29": "I don't make eye contact when I talk with people.",
    "Q30": "I have a monotone voice.",
    "Q31": "I am a touchy feely person.",
    "Q32": "I would like to try bungee jumping.",
    "Q33": "I tend to be admired by others.",
    "Q34": "I make big physical movements whenever I get excited.",
    "Q35": "I am brave.",
    "Q36": "I am always in the moment.",
    "Q37": "I am involved with my community.",
    "Q38": "I am good an entertaining children.",
    "Q39": "I like formal occasions.",
    "Q40": "I would have to be lost for a very long time before asking help.",
    "Q41": "I do not care about sports.",
    "Q42": "I prefer individual sports to team sports.",
    "Q43": "My parents know nothing about my love life.",
    "Q44": "I mostly listen to people in conversations.",
    "Q45": "I never leave the door to my room open.",
    "Q46": "I make a lot of hand motions when I talk.",
    "Q47": "I take lots of pictures of my activities.",
    "Q48": "When I was a child, I put on fake concerts and plays with my friends.",
    "Q49": "I really like dancing.",
    "Q50": "I would have difficulty describing myself to someone.",
    "Q51": "My life would not make a good story.",
    "Q52": "I am hesitant to give suggestions.",
    "Q53": "I tire out quickly.",
    "Q54": "I never tell people the important things about myself.",
    "Q55": "I avoid going to unknown places.",
    "Q56": "Going to the doctor is always awkward for me.",
    "Q57": "I have not kept up with my old friends over the years.",
    "Q58": "I have not been joyful for quite some time.",
    "Q59": "I hate to ask for help.",
    "Q60": "If I were to die, I would not want there to be a memorial for me.",
    "Q61": "I hate shopping.",
    "Q62": "I love to do impressions.",
    "Q63": "I would be pleased if asked to speak at a funeral.",
    "Q64": "I would never go to a dance club.",
    "Q65": "I find it very hard to tell people I find them attractive.",
    "Q66": "I hate people.",
    "Q67": "I was an outcast in school.",
    "Q68": "I would enjoy being a librarian.",
    "Q69": "I am usually not single.",
    "Q70": "I am able to stand up for myself.",
    "Q71": "I would go surfing regularly if I lived on a beach.",
    "Q72": "I have wanted to be a stand-up comedian.",
    "Q73": "I am a high status person.",
    "Q74": "I work out regularly.",
    "Q75": "I laugh a lot.",
    "Q76": "I like pranks.",
    "Q77": "I am happy with my life.",
    "Q78": "I am never at a loss for words.",
    "Q79": "I feel healthy and vibrant most of the time.",
    "Q80": "I love large parties.",
    "Q81": "I am quiet around strangers.",
    "Q82": "I don't talk a lot.",
    "Q83": "I keep in the background.",
    "Q84": "I don't like to draw attention to myself.",
    "Q85": "I have little to say.",
    "Q86": "I often feel blue.",
    "Q87": "I am not really interested in others.",
    "Q88": "I make people feel at ease.",
    "Q89": "I don't mind being the center of attention.",
    "Q90": "I start conversations.",
    "Q91": "I talk to a lot of different people at parties.",
}

In [3]:
questions = np.array(list(questions.values()))

In [4]:
questions[1]

'I am not much of a flirt.'

In [15]:
data = np.genfromtxt("data/dataset.csv", dtype=int, delimiter="\t")

In [16]:
data = data[1:, :]

In [18]:
print(data)
print(data.shape)
print(data.dtype)

[[   5   51 7107 ...    1   23    3]
 [   5   39 6354 ...    2   25    2]
 [   3   17 5397 ...    2   19    1]
 ...
 [   3   29 6618 ...    2   28    1]
 [   4   15 8321 ...    1   19    1]
 [   5   57 2950 ...    1   25    1]]
(7188, 282)
int64


In [34]:
questions[[0, 1, 2]]

array(['I would never audition to be on a game show.',
       'I am not much of a flirt.',
       'I have to psych myself up before I am brave enough to make a phone call.'],
      dtype='<U72')

In [40]:
data.shape

(7188, 282)

In [41]:
data[data < 12000].shape

(2006429,)

In [45]:
my_array = np.array(
    [[10, 2, 13], [21, 22, 23], [31, 32, 33], [10, 57, 20], [20, 20, 20], [101, 91, 10]]
)

In [48]:
def my_function(x):
#     position = np.argmax(x)
    position = np.max(x)

    return position

In [49]:
print(np.apply_along_axis(my_function, axis=0, arr=my_array))

[101  91  33]


In [99]:
df = pd.DataFrame(my_array)

0    101
1     91
2     33
dtype: int64


In [9]:
def my_function(x):
#     z= x.idxmax()
#     print(x[0], x[1], x[2])
    z= x.max()

    return z

In [ ]:
print(df.apply(my_function, axis=0))

In [74]:
df['yeni'] =df.apply(my_function, axis=1)

10 2 13
21 22 23
31 32 33
10 57 20
20 20 20
101 91 10


In [75]:
df

0   1   2  yeni
0   10   2  13    13
1   21  22  23    23
2   31  32  33    33
3   10  57  20    57
4   20  20  20    20
5  101  91  10   101

In [78]:
?df.nlargest

Signature: df.nlargest(n, columns, keep='first') -> 'DataFrame'
Docstring:
Return the first `n` rows ordered by `columns` in descending order.

Return the first `n` rows with the largest values in `columns`, in
descending order. The columns that are not specified are returned as
well, but not used for ordering.

This method is equivalent to
``df.sort_values(columns, ascending=False).head(n)``, but more
performant.

Parameters
----------
n : int
    Number of rows to return.
columns : label or list of labels
    Column label(s) to order by.
keep : {'first', 'last', 'all'}, default 'first'
    Where there are duplicate values:

    - `first` : prioritize the first occurrence(s)
    - `last` : prioritize the last occurrence(s)
    - ``all`` : do not drop any duplicates, even it means
                selecting more than `n` items.

    .. versionadded:: 0.24.0

Returns
-------
DataFrame
    The first `n` rows ordered by the given columns in descending
    order.

See Also
--------
DataFram

In [79]:
df.nlargest(3, 'yeni')

0   1   2  yeni
5  101  91  10   101
3   10  57  20    57
2   31  32  33    33

In [90]:
%%time
df.nsmallest(3, 'yeni')

CPU times: user 3.52 ms, sys: 0 ns, total: 3.52 ms
Wall time: 1.9 ms


0   1   2  yeni
0  10   2  13    13
4  20  20  20    20
1  21  22  23    23

In [86]:
%%time
df.sort_values('yeni', ascending=True).head(3)

CPU times: user 1.4 ms, sys: 226 µs, total: 1.62 ms
Wall time: 941 µs


0   1   2  yeni
0  10   2  13    13
4  20  20  20    20
1  21  22  23    23

In [10]:
%%time
df_2 = pd.DataFrame(np.random.randint(0,1000000,size=(150000, 4)), columns=list('ABCD'))

CPU times: user 3.4 ms, sys: 1.79 ms, total: 5.18 ms
Wall time: 3.83 ms


In [11]:
%%time
df_2

CPU times: user 2 µs, sys: 1 µs, total: 3 µs
Wall time: 4.29 µs


A       B       C       D
0       150585  998918  194920  760535
1       832780  977520  933415  473585
2       561704  316452  303296  817997
3       940847   65155   70238  265937
4       740735  922780  836565  616100
...        ...     ...     ...     ...
149995  911323  763350  774797  203463
149996  916565  407177  518233   21218
149997  517583  837872  339594  237872
149998  413803  789299   30317  700114
149999  733046  403663   40377  722079

[150000 rows x 4 columns]

In [12]:
%%time
df_2['yeni'] =df_2.apply(my_function, axis=1)

CPU times: user 7.14 s, sys: 513 ms, total: 7.65 s
Wall time: 7.2 s


In [13]:
df_2

A       B       C       D    yeni
0       150585  998918  194920  760535  998918
1       832780  977520  933415  473585  977520
2       561704  316452  303296  817997  817997
3       940847   65155   70238  265937  940847
4       740735  922780  836565  616100  922780
...        ...     ...     ...     ...     ...
149995  911323  763350  774797  203463  911323
149996  916565  407177  518233   21218  916565
149997  517583  837872  339594  237872  837872
149998  413803  789299   30317  700114  789299
149999  733046  403663   40377  722079  733046

[150000 rows x 5 columns]

In [19]:
%%time
df_2.sort_values('yeni', ascending=False).head(5)

CPU times: user 19.7 ms, sys: 137 µs, total: 19.9 ms
Wall time: 18.3 ms


A       B       C       D    yeni
43886  667848  577454  795917  999999  999999
11599  336243  221454  999998  184722  999998
60485  557803  999997  664558  265342  999997
9161   161822  999996  393976  296622  999996
16456  150939  851914  139009  999996  999996

In [18]:
%%time
df_2.nlargest(5, 'yeni')

CPU times: user 5.43 ms, sys: 797 µs, total: 6.23 ms
Wall time: 4.98 ms


A       B       C       D    yeni
43886  667848  577454  795917  999999  999999
11599  336243  221454  999998  184722  999998
60485  557803  999997  664558  265342  999997
9161   161822  999996  393976  296622  999996
9555   672347   38613   88633  999996  999996